In [12]:
import pandas as pd
import numpy as np
import os

In [3]:
###merge all state employment data into one
#create state map 
states =  pd.read_excel('state_abr.xlsx')

In [14]:
dir_path = 'state_employment_data/'
files = [f for f in os.listdir(dir_path) if os.path.isfile(os.path.join(dir_path, f))]
print(files)

['AK.xlsx', 'AL.xlsx', 'AR.xlsx', 'AZ.xlsx', 'CA.xlsx', 'CO.xlsx', 'CT.xlsx', 'DC.xlsx', 'DE.xlsx', 'FL.xlsx', 'GA.xlsx', 'HI.xlsx', 'IA.xlsx', 'ID.xlsx', 'IL.xlsx', 'IN.xlsx', 'KS.xlsx', 'KY.xlsx', 'LA.xlsx', 'MA.xlsx', 'MD.xlsx', 'ME.xlsx', 'MI.xlsx', 'MN.xlsx', 'MO.xlsx', 'MS.xlsx', 'MT.xlsx', 'NC.xlsx', 'ND.xlsx', 'NE.xlsx', 'NH.xlsx', 'NJ.xlsx', 'NM.xlsx', 'NV.xlsx', 'NY.xlsx', 'OH.xlsx', 'OK.xlsx', 'OR.xlsx', 'PA.xlsx', 'RI.xlsx', 'SC.xlsx', 'SD.xlsx', 'TN.xlsx', 'TX.xlsx', 'UT.xlsx', 'VA.xlsx', 'VT.xlsx', 'WA.xlsx', 'WI.xlsx', 'WV.xlsx', 'WY.xlsx']

In [69]:
#make a dictionary of each state name and DF
df_name = states['ABR']

dir_path = 'state_employment_data/'
files = [f for f in os.listdir(dir_path) if os.path.isfile(os.path.join(dir_path, f))]

datasets = {}
for i in range(0, len(df_name)):
    a = df_name[i]

    if f'{df_name[i]}.xlsx' in  os.listdir('state_employment_data/'):
        datasets[a] = pd.read_excel(f'state_employment_data/{a}.xlsx', skiprows = 2)
    else:
        continue

def add_county_column(df):
    df['County'] = df['Area'].apply(lambda x: str(x)[:-4])

for k, v in datasets.items():
    add_county_column(v)

c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [70]:
datasets['AL']

,Area,Industry,Occupation,Employment (1),County
0,"Anniston-Oxford, AL","Cross-Industry, Private, Federal, State, and L...",Management Occupations (11-0000),1840.0,Anniston-Oxford
1,"Anniston-Oxford, AL","Cross-Industry, Private, Federal, State, and L...",Business and Financial Operations Occupations ...,1850.0,Anniston-Oxford
2,"Anniston-Oxford, AL","Cross-Industry, Private, Federal, State, and L...",Computer and Mathematical Occupations (15-0000),420.0,Anniston-Oxford
3,"Anniston-Oxford, AL","Cross-Industry, Private, Federal, State, and L...",Architecture and Engineering Occupations (17-0...,660.0,Anniston-Oxford
4,"Anniston-Oxford, AL","Cross-Industry, Private, Federal, State, and L...","Life, Physical, and Social Science Occupations...",210.0,Anniston-Oxford
...,...,...,...,...,...
354,(1) Estimates for detailed occupations do not ...,NaN,NaN,NaN,(1) Estimates for detailed occupations do not ...
355,NaN,NaN,NaN,NaN,
356,SOC code: Standard Occupational Classification...,NaN,NaN,NaN,SOC code: Standard Occupational Classification...
357,NaN,NaN,NaN,NaN,
358,"Data extracted on October 02, 2026",NaN,NaN,NaN,"Data extracted on October 02,"

In [59]:

for k, v in datasets.items():
    print(k)

AL
AK
AZ
AR
CA
CO
CT
DE
DC
FL
GA
HI
ID
IL
IN
IA
KS
KY
LA
ME
MD
MA
MI
MN
MS
MO
MT
NE
NV
NH
NJ
NM
NY
NC
ND
OH
OK
OR
PA
RI
SC
SD
TN
TX
UT
VT
VA
WA
WV
WI
WY

In [61]:
datasets['DC'].head()

,Area,Industry,Occupation,Employment (1)
0,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Management Occupations (11-0000),2930.0
1,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Business and Financial Operations Occupations ...,3860.0
2,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Computer and Mathematical Occupations (15-0000),1400.0
3,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Architecture and Engineering Occupations (17-0...,990.0
4,"Dover, DE","Cross-Industry, Private, Federal, State, and L...","Life, Physical, and Social Science Occupations...",850.0

In [57]:
datasets['DC']

,Area,Industry,Occupation,Employment (1),County
0,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Management Occupations (11-0000),2930.0,Dover
1,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Business and Financial Operations Occupations ...,3860.0,Dover
2,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Computer and Mathematical Occupations (15-0000),1400.0,Dover
3,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Architecture and Engineering Occupations (17-0...,990.0,Dover
4,"Dover, DE","Cross-Industry, Private, Federal, State, and L...","Life, Physical, and Social Science Occupations...",850.0,Dover
5,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Community and Social Service Occupations (21-0...,1550.0,Dover
6,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Educational Instruction and Library Occupation...,5200.0,Dover
7,"Dover, DE","Cross-Industry, Private, Federal, State, and L...","Arts, Design, Entertainment, Sports, and Media...",520.0,Dover
8,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Healthcare Practitioners and Technical Occupat...,4530.0,Dover
9,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Healthcare Support Occupations (31-0000),3990.0,Dover
10,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Protective Service Occupations (33-0000),1430.0,Dover
11,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Food Preparation and Serving Related Occupatio...,6340.0,Dover
12,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Building and Grounds Cleaning and Maintenance ...,2410.0,Dover
13,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Personal Care and Service Occupations (39-0000),1520.0,Dover
14,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Sales and Related Occupations (41-0000),6110.0,Dover
15,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Office and Administrative Support Occupations ...,8850.0,Dover
16,"Dover, DE","Cross-Industry, Private, Federal, State, and L...","Farming, Fishing, and Forestry Occupations (45...",140.0,Dover
17,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Construction and Extraction Occupations (47-0000),2330.0,Dover
18,"Dover, DE","Cross-Industry, Private, Federal, State, and L...","Installation, Maintenance, and Repair Occupati...",2530.0,Dover
19,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Production Occupations (51-0000),3590.0,Dover
20,"Dover, DE","Cross-Industry, Private, Federal, State, and L...",Transportation and Material Moving Occupations...,6460.0,Dover
21,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Management Occupations (11-0000),3460.0,Sussex Delaware nonmetropolitan
22,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Business and Financial Operations Occupations ...,3820.0,Sussex Delaware nonmetropolitan
23,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Computer and Mathematical Occupations (15-0000),1020.0,Sussex Delaware nonmetropolitan
24,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Architecture and Engineering Occupations (17-0...,540.0,Sussex Delaware nonmetropolitan
25,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...","Life, Physical, and Social Science Occupations...",430.0,Sussex Delaware nonmetropolitan
26,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Community and Social Service Occupations (21-0...,1390.0,Sussex Delaware nonmetropolitan
27,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Educational Instruction and Library Occupation...,5510.0,Sussex Delaware nonmetropolitan
28,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...","Arts, Design, Entertainment, Sports, and Media...",680.0,Sussex Delaware nonmetropolitan
29,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Healthcare Practitioners and Technical Occupat...,6690.0,Sussex Delaware nonmetropolitan
30,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Healthcare Support Occupations (31-0000),4970.0,Sussex Delaware nonmetropolitan
31,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Protective Service Occupations (33-0000),1730.0,Sussex Delaware nonmetropolitan
32,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Food Preparation and Serving Related Occupatio...,14720.0,Sussex Delaware nonmetropolitan
33,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Building and Grounds Cleaning and Maintenance ...,4600.0,Sussex Delaware nonmetropolitan
34,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Personal Care and Service Occupations (39-0000),1980.0,Sussex Delaware nonmetropolitan
35,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Sales and Related Occupations (41-0000),11000.0,Sussex Delaware nonmetropolitan
36,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Office and Administrative Support Occupations ...,10030.0,Sussex Delaware nonmetropolitan
37,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...","Farming, Fishing, and Forestry Occupations (45...",450.0,Sussex Delaware nonmetropolitan
38,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Construction and Extraction Occupations (47-0000),4510.0,Sussex Delaware nonmetropolitan
39,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...","Installation, Maintenance, and Repair Occupati...",3840.0,Sussex Delaware nonmetropolitan
40,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Production Occupations (51-0000),8130.0,Sussex Delaware nonmetropolitan
41,Sussex Delaware nonmetropolitan area,"Cross-Industry, Private, Federal, State, and L...",Transportation and Material Moving Occupations...,7540.0,Sussex Delaware nonmetropolitan
42,NaN,NaN,NaN,NaN,
43,Footnotes:,NaN,NaN,NaN,Footno
44,(1) Estimates for detailed occupations do not ...,NaN,NaN,NaN,(1) Estimates for detailed occupations do not ...
45,NaN,NaN,NaN,NaN,
46,SOC code: Standard Occupational Classification...,NaN,NaN,NaN,SOC code: Standard Occupational Classification...
47,NaN,NaN,NaN,NaN,
48,"Data extracted on October 02, 2026",NaN,NaN,NaN,"Data extracted on October 02,"

In [40]:
alaska = pd.read_excel(f'state_employment_data/AK.xlsx', skiprows = 2)

c:\Users\annas\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [36]:
alaska['County'] = alaska['Area'].apply(lambda x: str(x)[:-4])

In [ ]:
zip(df_name, x)

In [20]:
df_name[0]

'AL'